app_url=https://nikita-filonov.github.io/qa-automation-engineer-ui-course
headless=False
browsers=[<Browser.CHROMIUM: 'chromium'>, <Browser.WEBKIT: 'webkit'>]
test_user={'email': 'user.name@gmail.com', 'username': 'username', 'password': 'password'}
test_data={'image_png_file': WindowsPath('testdata/files/image.png')}
videos_dir=videos
tracing_dir=tracing
allure_results_dir=allure-results
browser_state_file=browser-state.json